# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c90de27286becf79f5bc7c3358e3fcf0da2b9b064709259e1b37fee4f0e9169a1b969536ec79bb879ca89fa7a1f157c5ff123dff3edde8ba9755360bf89a3ee

test:
  secret_key_base: 099aa6795fe6d87f691655d0c9ba41fc06ec64e4c33a723f6437381f614d7c8c63a0ffe80e717f41bde607a40e294195a25fb1651fac649151144598af226ada

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
